GET http://localhost:5000/ads

###

POST http://localhost:5000/ads
Content-Type: application/json

{
    "title": "205 a vendre",
    "description":
      "My skateboard is green, working fine. I'm selling it because I've got a new one",
    "owner": "skateboard.seller@gmail.com",
    "price": 100,
    "picture":
      "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Reims",
"createdAt": "2024-02-27T10:17:15.922Z"
  }

###

DELETE http://localhost:5000/ads/7

###

PUT http://localhost:5000/ads/3
Content-Type: application/json

{
        "id": 3,
    "title": "Skateboard to sell",
    "description":
      "My skateboard is green, working fine. I'm selling it because I've got a new one",
    "owner": "skateboard.seller@gmail.com",
    "price": 200,
    "picture":
      "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "Reims",
"createdAt": "2024-02-27T10:17:15.922Z"
}
