GET http://localhost:5000/ads
###

GET http://localhost:5000/search/ads/205

###

GET http://localhost:5000/ads/2

###

POST http://localhost:5000/ads
Content-Type: application/json

{
    "title": "ce titre est trop long et va provoquer une erreur de validation",
    "description":
      "My skateboard is green, working fine. I'm selling it because I've got a new one",
    "owner": "skateboard.seller@gmail.com",
    "price": 100,
    "picture":
      "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "ville": "Reims",
  "createdAt": "2024-02-27T10:17:15.922Z",
  "category": 2,
  "tags": [1,2]
  }

###

DELETE http://localhost:5000/ads/1

###

PUT http://localhost:5000/ads/1
Content-Type: application/json

{
  "title": "new title 2"
}

